name: hello-world

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Step
        run: echo "demo build"

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test Step
        run: echo "demo test"

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Step
        run: echo "deploy"
